name: Run Node.js Script

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Starting the script..."
          node index.js